apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld2
spec:
  selector:
    matchLabels:
      app: helloworld2
  replicas: 1 
  template: 
    metadata:
      labels:
        app: helloworld2
    spec:
      containers:
      - name: helloworld2
        image: pavirenga/helloworld:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: helloworld2
spec:
 type: NodePort
 selector:
   app: helloworld2
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32080
 selector:
   app: helloworld2
